### ISSUE TITLE
Free Data API: how to use it?

### ISSUE THREAD

**Issue by aborruso** [gitrows/gitrows#1]
Hi,
I have tried to use free data api, starting from https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv

But the Public API Url https://api.gitrows.com/@github/pcm-dpc/COVID-19/dati-regioni/dpc-covid19-ita-regioni.csv gives me "502 Bad Gateway".

Is it ok? Am I doing something wrong?

Thank you for this project

![image](https://user-images.githubusercontent.com/30607/83106680-2e0ba680-a0bd-11ea-91f1-5608ba063145.png)

**Comment by nicolaszimmer** [comment]
Hi Andrea,

There was bug in the compression function for larger data sets in the public api which has been resolved. You should be able now to fetch the data.

**Comment by aborruso** [comment]
Thank you
