### ISSUE TITLE
CSV delimiter, quoting & options

### ISSUE THREAD

**Issue by franky47** [gitrows/gitrows#10]
**Describe the bug**

The `csv.delimiter` option is not used in the `CSV.stringify` call.

Also, it could be useful to quote strings, that may contain delimiter characters:
https://csv.js.org/stringify/options/quoted_string/

**To Reproduce**

Using the default comma delimiter, try to push a CSV row containing a comma:
```ts
gitrows.put(path, { test: "Hello, World" })
```

This returns an error `Uncaught (in promise) DOMException: String contains an invalid character`.

**Expected behavior**

- Ability to change the default delimiter (eg: to `;`)
- Quoting strings that may contain the delimiter

**Proposed change**

Pass the `csv` option in GitRows to `CSV.stringify` directly.

This would solve the delimiter issue, and allow to specify other CSV options, such as:
```ts
gitrows.options({
  csv: {
    delimiter: ';',
    quoted_string: true,
    cast: {
      date: value => value.toISOString()
    }
  }
})
```

If this change is acceptable, I can open a PR.

**Desktop**
 - OS: macOS
 - Browser: Firefox 84
 - Version: 0.8.0

**Comment by nicolaszimmer** [comment]
Thanks, please open the PR
