### ISSUE TITLE
Free Data API: not able to apply filters

### ISSUE THREAD

**Issue by aborruso** [gitrows/gitrows#2]
Hi,
if I run `curl https://api.gitrows.com/@github/pcm-dpc/COVID-19/dati-json/dpc-covid19-ita-regioni.json?codice_regione=lt:3` I have "502 Bad Gateway"

I'm adding a related question: what's the equal numeric operator? Is it simply `=`?

If yes also this command `curl https://api.gitrows.com/@github/pcm-dpc/COVID-19/dati-json/dpc-covid19-ita-regioni.json?codice_regione=19` gives to me "502 Bad Gateway".

Thank you

**Comment by nicolaszimmer** [comment]
Hi Andrea,

Sorry for the hassle, it's now working again as expected. 

The equal numeric operator is indeed `=`
