### ISSUE TITLE
400 error

### ISSUE THREAD

**Issue by aborruso** [gitrows/gitrows#20]
Hi,
If I call https://api.gitrows.com/@github/gabacode/f8lite:main/dati-comuni/dpc-covid19-ita-pa-82004.csv I have

```
{
  "code": 400,
  "message": "Bad Request",
  "documentation": [
    {
      "description": "HTTP Status Codes",
      "url": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400"
    },
    {
      "description": "GitRows API Documentation",
      "url": "https://gitrows.com/docs/api/path"
    }
  ]
}
```

Thank you

**Comment by dindinet** [comment]
I think you have a missing zero in the url **0**82004.csv

Also you included the branch name after the repo name f8lite:main remove the branch name :main

this works https://api.gitrows.com/@github/gabacode/f8lite/dati-comuni/dpc-covid19-ita-pa-082004.csv

**Comment by aborruso** [comment]
> I think you have a missing zero in the url **0**82004.csv

No, when I opened the issue it the name was `82004` https://github.com/gabacode/f8lite/tree/e2239f5ad5429cd0ac51e5349aeacd560e0ed6b6/dati-comuni

> Also you included the branch name after the repo name f8lite:main remove the branch name :main

You are right there is a problem in the linter. I'm opening a new issue

![image](https://user-images.githubusercontent.com/30607/119147287-ba8c4300-ba4b-11eb-8049-99de69913a77.png)
