### ISSUE TITLE
Case insensitive Filtering 

### ISSUE THREAD

**Issue by aborruso** [gitrows/gitrows#3]
**Describe the solution you'd like**

If I search "COVID" [here](https://api.gitrows.com/@github/opendatasicilia/RSSdisegniLeggeAssembleaRegionaleSiciliana/docs/storico.csv?titolo=*:COVID) I have no result, because in the source is "[Covid](https://api.gitrows.com/@github/opendatasicilia/RSSdisegniLeggeAssembleaRegionaleSiciliana/docs/storico.csv?titolo=*:Covid)".

I would like to have case insensitive filtering by default or as an option, because the text string I am looking for could be written in many different ways ("covid", "Covid", "COVID", ...) and I will only get a result if I'm lucky.

Thank you

**Comment by nicolaszimmer** [comment]
Thanks, Andrea, I‘ll add this with the upcoming release in the next few days!

**Comment by aborruso** [comment]
Thank you very much
