### ISSUE TITLE
Docker Container for a full quick start of the api !

### ISSUE THREAD

**Issue by Sanix-Darker** [gitrows/gitrows#35]
**Is your feature request related to a problem? Please describe.**
Not really but for a quick start project, it could be nice to have a docker container for githubrows that start a full restfull api

**Describe the solution you'd like**
I would like to add that to the project but i wanted to know if it's on the roadmap at the first place, i mean something like...
```dockerfile
FROM node:12.18.1
ENV NODE_ENV=production

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install --production

COPY . .

CMD [ "node", "server.js" ]
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Sanix-Darker** [comment]
Soooo.... i finaly decided to make it myself lol !
https://github.com/Sanix-Darker/gitrowspack-api

With some adjustments, fix, corrections and improvements !

**Comment by nicolaszimmer** [comment]
Well done @Sanix-Darker !
