### ISSUE TITLE
Is it possible to connect with a local git repo?

### ISSUE THREAD

**Issue by saru2020** [gitrows/gitrows#40]
Is it possible to connect with a local git repo instead of github or gitlab? if yes, then references please

**Comment by saru2020** [comment]
is this a possibility? @nicolaszimmer @detj @franky47 @Sanix-Darker

**Comment by Sanix-Darker** [comment]
gitrows is based on github/gitlab API to CRUD the repository... if am not wrong... but i think it's possible to interract with a local repo, it really depends what you mean by "local" and what is the middleware that will CRUD on that "local repo !"

on gitrows, the middleware is github/gitlab apis...

**Comment by nicolaszimmer** [comment]
Sorry for the late reply, @saru2020 Connecting it to a local git repo is currently not in the scope of gitrows. As this library relies on the rest APIs for getting the data stream, you can probably make it work by either having a local http server and API running or extending the methods to access the local repo with something like https://github.com/nodegit/nodegit
