### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by aborruso** [gitrows/gitrows#8]
Hi,
when I open https://api.gitrows.com/@github/aborruso/firstaction/openregio_immobiliDestinati.csv I have "502 Bad Gateway".

Is it normal?

Thank you

**Comment by nicolaszimmer** [comment]
Hi Andrea, as it's a pretty large file, the lambda function was not able to forward the result set. It's fixed now, I've added zlib compression to the result set for transfer, that will be unzipped again on the client side, e.g. if you're using the browser (js). However if the client request does not include the accept-encoding: gzip header (automatically so with browser requests), the request may still fail.

**Comment by aborruso** [comment]
Thank you very much
